# Generated by Django 4.2.23 on 2025-08-05 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='reportado_por',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='ticket_unico',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='incidencia',
            name='ubicacion',
        ),
    ]
