# Generated by Django 4.2.23 on 2025-08-05 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportes_app', '0002_remove_incidencia_asignado_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='descripcion',
            field=models.TextField(default='descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes_app.estado'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='prioridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportes_app.prioridad'),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='reportado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='ticket_unico',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='titulo',
            field=models.CharField(default='titulo', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incidencia',
            name='ubicacion',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
